# Generated by Django 4.0.2 on 2022-10-21 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_possible_result_outcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Botgame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
                ('maximumscore', models.IntegerField(default=3)),
                ('letter', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=64)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_result', to='categories.possible_result')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
