# Generated by Django 4.0.2 on 2022-10-21 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_botgame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botgame',
            name='category',
        ),
        migrations.RemoveField(
            model_name='botgame',
            name='letter',
        ),
        migrations.RemoveField(
            model_name='botgame',
            name='user',
        ),
        migrations.AddField(
            model_name='botgame',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
